DROP TABLE IF EXISTS contact_card;
DROP TABLE IF EXISTS user_login;

CREATE TABLE contact_card (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone_number VARCHAR(255) NOT NULL,
  -- address VARCHAR(255) NOT NULL,
  -- city VARCHAR(255) NOT NULL,
  -- state VARCHAR(255) NOT NULL,
  -- zip VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL
--   CONSTRAINT fk_dep FOREIGN KEY (dep_id) REFERENCES departments(id) ON DELETE SET NULL
);

CREATE TABLE user_login (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL,
    passw VARCHAR(50) NOT NULL,
-- CONSTRAINT fk_dep FOREIGN KEY (dep_id) REFERENCES departments(id) ON DELETE SET NULL
);